config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get    "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  get    "search",   to: "static_pages#search"
  get    "creature_search",   to: "creatures#search", as: "creature_search"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :creatures
  resources :spots
  resources :prefectures, only: [:show] do
    resources :spots, only: [:show]
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :prefecture
  has_and_belongs_to_many :creatures

  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 500 }
  validate :image_format
  mount_uploader :image, ImageUploader

  private

  def image_format
    return if image.blank?
      acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "must be a JPEG or PNG")
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update]

  def index
    @prefectures = Prefecture.includes(:spots).order(:name)
  end

  def show
    @prefecture = @spot.prefecture
    @creatures = @spot.creatures
  end

  def edit
    # @spotはbefore_actionで設定されている
    @creatures = Creature.all # 全ての生き物を取得
  end

  def update
    if @spot.update(spot_params)
      flash[:success] = t('flash.success.spot_updated')
      redirect_to @spot
    else
      render :edit
    end
  end

  private

  def set_spot
    @spot = Spot.includes(:creatures).find(params[:id])
  end

  def spot_params
    params.require(:spot).permit(:name, :address, :description, :image, :prefecture_id, creature_ids: [])
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/edit.html.erb
<%= stylesheet_link_tag 'views/spots-edit', 'media' => 'all', 'data-turbo-track': 'reload' %>
<% provide(:title, @spot.name) %>

<%= form_with(model: @spot, local: true) do |form| %>
  <div class="spot-form">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-textarea" %>
    </div>

    <div class="form-group creatures-select">
      <%= form.label :creatures, "生き物を選択" %>
      <div class="creatures-checkboxes">
        <%= form.collection_check_boxes :creature_ids, @creatures, :id, :name do |b| %>
          <div class="creature-checkbox-item">
            <div class="creature-info">
              <% if b.object.photo.present? %>
                <%= image_tag b.object.photo.url(:thumb), class: "creature-image" %>
              <% end %>
              <div>
                <%= b.check_box %>
                <%= b.label %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% if @spot.errors.any? %>
      <div class="error-messages">
        <h2>エラー</h2>
        <ul>
          <% @spot.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.submit "更新", class: "btn btn-primary" %>
    <%= link_to '戻る', spot_path(@spot), class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/spots/index.html.erb
<%= stylesheet_link_tag 'views/spots-index', 'media' => 'all', 'data-turbo-track': 'reload' %>
<% provide(:title, "List of Diving Spots") %>

<div class="container">
  <h1>ダイビングスポット一覧</h1>
  <div class="row">
    <% @prefectures.each do |prefecture| %>
      <% if prefecture.spots.any? %>
        <div class="col-md-12">
          <h2 class="prefecture-name"><%= prefecture.name %></h2>
          <div class="row">
            <% prefecture.spots.each do |spot| %>
              <div class="col-md-4 col-6">
                <div class="spot-item">
                  <%= image_tag spot.image.url(:thumb), class: 'spot-image' if spot.image.present? %>
                  <h3><%= link_to spot.name, prefecture_spot_path(prefecture, spot), class: 'spot-link' %></h3>
                  <p class="spot-description">住所: <%= spot.address %></p>
                  <p class="spot-description">説明: <%= spot.description %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spots/show.html.erb
<%= stylesheet_link_tag 'views/spots-show', 'media' => 'all', 'data-turbo-track': 'reload' %>
<% provide(:title, @spot.name) %>

<div class="spot-show-container container">
  <div class="spot-info text-center">
    <input id="address" value="<%= @spot.address %>">

    <div class="map-container">
      <div id="map" style="height: 500px; width: 100%;"></div>
    </div>

    <h1 class="spot-title mt-3"><%= @spot.name %></h1>
    <p class="mb-1">住所: <%= @spot.address %></p>
    <p>説明: <%= @spot.description %></p>

    <div class="spot-actions mt-3">
      <%= link_to 'スポット一覧に戻る', prefecture_path(@spot.prefecture_id), class: 'back-link btn btn-primary' %>

      <% if logged_in? %>
        <%= link_to 'スポットを編集する', edit_spot_path(@spot), class: 'edit-link btn btn-secondary ml-2' %>
      <% end %>
    </div>
  </div>

  <div class="creatures-section mt-5">
    <h2 class="text-center">このスポットにいる生き物</h2>
    <% if @creatures.any? %>
      <div class="row">
        <% @creatures.each do |creature| %>
          <div class="col-md-3 mb-4">
            <div class="creature-item border p-3 rounded shadow-sm text-center">
              <h4><%= link_to creature.name, creature %></h4>
              <%= image_tag creature.photo.url(:thumb), class: 'creature-image img-fluid mb-2' if creature.photo.present? %>
              <p><%= creature.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="text-center">このスポットには生き物がいません。</p>
    <% end %>
  </div>
</div>
<%= javascript_import_module_tag "custom/spots_show" %>
<script
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap">
</script>