config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get    "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  get    "search",   to: "static_pages#search"
  get    "creature_search",   to: "creatures#search", as: "creature_search"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :creatures
  resources :spots
  resources :prefectures, only: [:show] do
    resources :spots, only: [:show]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @prefectures = Prefecture.all
    @creatures = Creature.all
    @prefectures = Prefecture.joins(:spots).distinct.order(:name)
    @prefectures_with_spots = Prefecture.joins(:spots).distinct.pluck(:id)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<%= stylesheet_link_tag 'views/home', 'media' => 'all', 'data-turbo-track': 'reload' %>

<div class="center">
  <section class="logo-container">
    <%= image_tag 'scuba_diving_logo.png', alt: 'Scuba Diving Spots Logo', class: 'logo-image' %>
    <h1 class="logo-text">ScubaDivingSpots</h1>
  </section>

  <section id="map" class="custom-container">
    <h1>日本地図</h1>
    <div id="jmap" data-controller="home" data-prefectures-with-spots="<%= @prefectures_with_spots.to_json %>">
      <div class="jmap-infobox">
        <h3>ダイビングポイント</h3>
        <p>地図をクリックするとダイビングスポットが表示されます。</p>
      </div>
    </div>
  </section>

  <section class="custom-container">
    <h1>都道府県一覧から探す</h1>
    <div class="prefectures-container">
      <% @prefectures.each do |prefecture| %>
        <div class="prefecture-item">
          <%= link_to prefecture.name, prefecture_path(prefecture), class: "prefecture-link" %>
        </div>
      <% end %>
    </div>
  </section>

  <section class="custom-container">
    <h1>生き物を探す</h1>
    <div class="search_form">
      <%= form_with url: creature_search_path, method: :get, local: true do %>
        <div class="form-group">
          <%= label_tag :query, "生き物の名前" %>
          <%= text_field_tag :query, params[:query], class: "form-control" %>
        </div>
        <div class="form-group">
          <%= submit_tag "検索", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>

    <div class="spot-show-container container">
      <div class="creatures-section mt-5">
        <h2>生き物一覧</h2>
        <div class="row">
          <% @creatures.each_with_index do |creature, index| %>
            <div class="col-md-4 mb-4">
              <div class="creature-item border p-3 rounded shadow-sm text-center">
                <h4><%= link_to creature.name, creature_path(creature) %></h4>
                <%= image_tag creature.photo.url(:thumb), class: 'creature-image img-fluid mb-2' if creature.photo.present? %>
                <p><%= creature.description %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>