config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get    "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  get    "search",   to: "static_pages#search"
  get    "creature_search",   to: "creatures#search", as: "creature_search"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :creatures
  resources :spots
  resources :prefectures, only: [:show] do
    resources :spots, only: [:show]
  end
end

app/models/creature.rb
class Creature < ApplicationRecord
  has_and_belongs_to_many :spots

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :periods, presence: true, length: { maximum: 200 }
  validate :photo_format

  mount_uploader :photo, PhotoUploader

  private

  def photo_format
    return if photo.blank?
    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(photo.content_type)
      errors.add(:photo, "must be a JPEG or PNG")
    end
  end
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: %i[show edit update destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @creatures = Creature.all
  end

  def show
  end

  def new
    @creature = Creature.new
  end

  def edit
  end

  def create
    @creature = Creature.new(creature_params)
    if @creature.save
      redirect_to @creature
      flash[:success] = t('flash.success.creature_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def search
    if params[:query].present?
      @creatures = Creature.where("name LIKE ?", "%#{params[:query]}%")
    else
      @creatures = Creature.all
    end
  end

  def update
    if @creature.update(creature_params)
      redirect_to @creature
      flash[:success] = t('flash.success.creature_updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @creature.destroy
    redirect_to creatures_url,
    flash[:success] = t('flash.success.creature_deleted')
  end

  private

  def set_creature
    @creature = Creature.find(params[:id])
  end

  def creature_params
    params.require(:creature).permit(:name, :description, :periods, :photo, spot_ids: [])
  end
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/edit.html.erb
<%= stylesheet_link_tag 'views/creatures-edit', 'media' => 'all', 'data-turbo-track': 'reload' %>
<% provide(:title, @creature.name) %>

<h1 class="edit-creature-title">編集</h1>

<%= form_with(model: @creature, local: true, class: 'creature-form') do |form| %>
  <% if @creature.errors.any? %>
    <div id="error_explanation" class="error-messages">
      <h2><%= pluralize(@creature.errors.count, "error") %> prohibited this creature from being saved:</h2>
      <ul>
        <% @creature.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>名前</p>
    <%= form.text_field :name, class: 'form-input' %>
  </div>

  <div class="field">
    <p>説明</p>
    <%= form.text_area :description, class: 'form-textarea' %>
  </div>

  <div class="field">
    <p>時期</p>
    <%= form.text_area :periods, class: 'form-textarea' %>
  </div>

  <div class="field">
    <%= form.label :photo, class: 'form-label' %>
    <%= form.file_field :photo, class: 'form-input' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Creature', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', creatures_path, class: 'btn btn-secondary' %>

app/views/creatures/index.html.erb
<%= stylesheet_link_tag 'views/creatures-index', 'media' => 'all', 'data-turbo-track': 'reload' %>
<% provide(:title, "生き物一覧") %>

<h1 class="creature-title">生き物一覧</h1>
  <% if logged_in? %>
    <%= link_to '新規作成', new_creature_path, class: 'btn btn-primary new-creature-link' %>
  <% end %>

<table class="creature-table">
  <thead>
    <tr>
      <th>名前</th>
      <th>説明</th>
      <th>時期</th>
      <th>写真</th>
      <th>作業</th>
    </tr>
  </thead>
  <tbody>
    <% @creatures.each do |creature| %>
      <tr>
        <td><%= creature.name %></td>
        <td><%= creature.description %></td>
        <td><%= creature.periods %></td>
        <td class="creature-photo-cell">
          <%= image_tag creature.photo.url(:thumb), class: 'creature-image' if creature.photo.present? %>
        </td>
        <td>
          <%= link_to '詳細', creature, class: 'btn btn-info' %>
          <% if logged_in? %>
            <%= link_to '編集', edit_creature_path(creature), class: 'btn btn-secondary' %>
            <%= link_to '削除', creature, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/creatures/new.html.erb
<%= stylesheet_link_tag 'views/creatures-new', 'media' => 'all', 'data-turbo-track': 'reload' %>
<% provide(:title, "新規作成") %>

<h1>新規作成</h1>

<%= form_with(model: @creature, local: true) do |form| %>
  <%= render 'shared/creature_error_messages', object: @creature %>

  <div class="field">
    <p>名前</p>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <p>時期</p>
    <%= form.text_area :periods %>
  </div>

  <div class="field">
    <p>説明</p>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <p>写真</p>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', creatures_path %>

app/views/creatures/search.html.erb
<%= stylesheet_link_tag 'views/spots-show', 'media' => 'all', 'data-turbo-track': 'reload' %>
<% provide(:title, "生き物検索") %>

<div class="spot-show-container container">
  <div class="creatures-section mt-5">
    <h2 class="text-center">生き物検索結果</h2>
    <% if @creatures.any? %>
      <div class="row">
        <% @creatures.each do |creature| %>
          <div class="col-md-3 mb-4">
            <div class="creature-item border p-3 rounded shadow-sm text-center">
              <h4><%= link_to creature.name, creature_path(creature) %></h4>
              <%= image_tag creature.photo.url(:thumb), class: 'creature-image img-fluid mb-2' if creature.photo.present? %>
              <p><%= creature.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="text-center">該当する生き物が見つかりませんでした。</p>
    <% end %>
  </div>
</div>
  <%= link_to 'Back', creatures_path %>

app/views/creatures/show.html.erb
<%= stylesheet_link_tag 'views/creatures-show', 'media' => 'all', 'data-turbo-track': 'reload' %>
<% provide(:title, @creature.name) %>

<div class="creature-details-container">
  <h1 class="creature-title"><%= @creature.name %></h1>

  <div class="creature-info">
    <div class="creature-photo">
      <%= image_tag @creature.photo.url(:thumb), class: 'creature-image' if @creature.photo? %>
    </div>
    <p><strong>時期:</strong> <%= @creature.periods %></p>
    <p><strong>説明:</strong> <%= @creature.description %></p>
  </div>

  <div class="creature-actions">
    <% if logged_in? %>
      <%= link_to 'Edit', edit_creature_path(@creature), class: 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Back', creatures_path, class: 'btn btn-secondary' %>
  </div>
</div>